language: node_js

node_js:
  - "stable"

cache:
  directories:
    - "node_modules"

install:
  - npm install
  - npm install -g firebase-tools
  - git clone https://github.com/Shivansh2407/VITHack-Frontend ./

script:
  - npm run build
  - firebase deploy
