language: node_js

node_js:
  - "stable"

cache:
  directories:
    - "node_modules"

install:
  - ls

script:
  - git clone https://github.com/Shivansh2407/VITHack-Frontend repo
  - npm install --prefix repo/
  - npm run build --prefix repo/
  - npm install -g git://github.com/firebase/firebase-tools#master
  - firebase deploy
