language: node_js

node_js:
  - 14

cache:
  directories:
    - 'node_modules'

install:
  - ls

script:
  - git clone https://github.com/Shivansh2407/VITHack-Frontend repo
  - yarn install --cwd repo/
  - yarn --cwd repo/ build
  - npm install -g git://github.com/firebase/firebase-tools#master
  - firebase deploy --token "$FIREBASE_TOKEN"
